server:
  port: 8086

spring:
  application:
    name: application

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

    config:
      uri: http://configserver:password@config-server-service:8888

  config:
    import: "optional:config:"

  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      host: mongodb-service
      port: 27017
      database: application

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
