apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: post
spec:
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: duycoiz1204/jobnet-ipj-post:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "384Mi"
              cpu: "500m"
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: awss3-secret
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: awss3-secret
                  key: secret_access_key

---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels:
    app: post
spec:
  selector:
    app: post
  ports:
    - port: 8083
      targetPort: 8083
