apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: duycoiz1204/jobnet-ipj-user:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "384Mi"
              cpu: "500m"
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: awss3-secret
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: awss3-secret
                  key: secret_access_key

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
